# FDRAS debug config (no CT main, CT+mask for error maps)

data_root: "D:/Francis/Luma/seg_qa/runs/CT_Training_Data/ATM_Data"
ct_subdir: "imagesTr"
pred_subdir: "nnUNet_masksTr"
val_pred_subdir_alt: "TfeNet_masksTr"
gt_subdir: "labelsTr"
val_count: 0
test_count: 0
seed: 42

train_case_ids:
  - "ATM_001_0000"
  - "ATM_002_0000"
  - "ATM_003_0000"
  - "ATM_004_0000"
overfit_use_train_as_val: false

val_data_roots:
  - "D:/Francis/Luma/seg_qa/runs/CT_Training_Data/ARIC_Data"
val_sample_csv: "D:/Francis/Luma/seg_qa/runs/CT_Training_Data/ARIC_Data/nnunet_quality_per_case.csv"
val_sample_metric: "Dice"
val_sample_n: 1
val_sample_bins: 2
val_sample_seed: 42

train_extra_subdirs:
  - "nnUNet_masksTr_TreeErrTr"
  - "nnUNet_masksTr_SDFErrTr"
val_extra_subdirs: []

ct_window_min: -1000.0
ct_window_max: 300.0

patch_size: [96, 96, 96]
batch_size: 1
num_workers: 0
use_pos_neg_crop: true
pos_ratio: 9
neg_ratio: 1
num_samples: 1
flatten_samples: false
expand_epoch_samples: true
repeat_per_case: 10
use_persistent_cache: true
cache_dir: "runs/fdras_debug_cache"
train_full_volume: false
val_full_volume: true
val_use_sliding_window: true
sw_overlap: 0.5
sw_batch_size: 1
train_use_sliding_window: false
train_sw_overlap: 0.5
train_sw_batch_size: 1
train_use_grid_patch: false
train_grid_overlap: 0.25
train_use_rand_grid_patch: false
train_rand_grid_overlap: 0.0
train_rand_grid_num_patches: 1
use_ct_input: false
err_use_ct_input: true
fixer_use_ct_input: false

base_channels: 16
err_base_channels: 8
fix_base_channels: 8
fixer_type: "cross_attn_no_ct"
norm: "INSTANCE"
num_res_units: 1

w_l1: 0.0
w_dice: 2.0
w_bce: 1.0
w_err_l1: 1.0
w_err_bce: 1.0
w_cldice: 0.0
w_ccf: 0.0
w_consistency: 0.0
w_gan: 0.0
cldice_iters: 3
ccf_iters: 3

epochs: 20
lr_g: 0.001
lr_d: 0.001
weight_decay: 0.00001
val_every: 1
val_max_batches: 0
val_repeat_per_case: 1
save_val_case_id: null
save_val_out_dir: "runs/fdras_debug/epoch_preds_no_ct_cross_attn_ct_err"
save_val_every: 1
save_val_prob: true
save_val_mask: true
save_val_err_pred: true

amp: false
device: "cuda"

out_dir: "runs/repair_model/fdras_debug_no_ct_cross_attn_ct_err"
save_every: 5
use_tqdm: true

use_wandb: true
wandb_project: "fdras-debug"
wandb_entity: "francis-xiatian-zhang-sirg"
wandb_run_name: null
wandb_tags: ["debug", "fdras", "no_ct", "cross_attn", "ct_err"]
